### ISSUE TITLE
Does *generate SGF from SVG* or *use pure SVG to read/write kifu files* make sense?

### ISSUE THREAD

**Issue by HackYardo** [julianandrews/sgf-render#22]
- I am looking for a technical roadmap to realize **the read/write of the full information of an analyzed kifu**. 
- A complete kifu can be render in an image in a Go book.pdf, why not conversely(SVG is editable)? 
- Why not SGF or why SVG? It seems that the SGF standard doesn't change since [2007](https://www.red-bean.com/sgf/history.html). However, the Go analysis has changed since AlphaGo 2016. The information of an analyzed kifu are much more than ever, i.e. win-rate, visit/playout, ownership, see [KataGo GTP Extensions](https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md) for more.

**Comment by julianandrews** [comment]
You absolutely could encode any information you want in an SVG - it's just an XML doc, and there are a few different ways to do that.

That said, the SVG will include a lot of display specific information that it really doesn't make sense to include in a game record, making it an inefficient and noisy way to store a kifu. The SGF format allows storing extra information in user defined properties (see the [spec](https://www.red-bean.com/sgf/sgf4.html#2.2)), so if I were looking to store kifu collections with extra metadata, that's definitely how I would do it.

Alternatively, you could just store the metadata in SGF `C[]` tags, in which case it should be displayed by a lot of software that works with SGFs. That might make more sense if the intention is to make the metadata human readable rather than computer readable.

**Comment by HackYardo** [comment]
Thanks a lot.
If can generate SGF from SVG, it can be used as some kind **"pseudo image recognition"**. :joke
But one simple SVG can not be used as SGF because there are no tree structures in a static image.
However, I think it could be solved by containing multiple subplots in an image, e.g. the main path of a Go game as the main subplot, and branch paths as the subplots. In this way, **one (svg) image corresponds to one sgf text**. I will try it in the following three years.
Why I go round such a big circle? An image is more readable to mankind than a text, otherwise people use CLI terminals to play games rather than GUIs...
