### ISSUE TITLE
first line of annotation text is outside the box

### ISSUE THREAD

**Issue by AprilInParis** [julianandrews/sgf-render#32]
![4](https://github.com/julianandrews/sgf-render/assets/154599603/2f23e66e-7b24-4fd1-a2e9-33dd5243eb48)

opened new issue, ref: https://github.com/julianandrews/sgf-render/issues/29

The first line of annotation text is outside the box.

Thanks for the quick response. I've put a link on Sensei library for sgf-render as I'm sure others will find it useful too. 
Neil

**Comment by AprilInParis** [comment]
Tried it on Chrome and it renders ok.

Firefox, Atril, Gimp all show the problem above.

**Comment by julianandrews** [comment]
For a little more info, the SVGs render correctly in Inkscape, but not in `feh` or when rendering to PNG.

I think the issue is with support for the `alignment-baseline` property. I render the text using `alignment-baseline="hanging"`, but I don't think that property is broadly supported. The solution here will be to use the default vertical alignment, and to position the text appropriately.

**Comment by julianandrews** [comment]
Fix pushed!

**Comment by julianandrews** [comment]
New release (v2.4.3) should have the fix.

Thanks for spotting these bugs! I haven't really had cause to hand-test kifu mode very much, and as a result there's a little less polish than the other modes. It's nice to get a chance to start bringing it up to speed.
