### ISSUE TITLE
Get number of variations / games or last variation / game in SGF

### ISSUE THREAD

**Issue by vabue** [julianandrews/sgf-render#40]
Hello,

First of all I want to thank you for your work on sgf-render. It's real time-saver if you want to print sgf diagram! 

I often print all the variants of the SGF diagram, and for that it would be really great to have query command output the total number of variations and games in the current SGF file. The goal is to be able to easily script output of all the sgf variations. It is possible to do now with a little awk / grep, but native support would be easier to use.

Something like:
`sgf-render query --last-variation`
`sgf-render query --last-game`

**Comment by julianandrews** [comment]
I think this is a great idea.

Part of the motivation of adding the `query` command was to enable more scripting/command line use, and this seems like a natural step, and I like the suggested interface as is.

For future reference, I considered the 'count' versions of each of these (e.g. `sgf-render query --variation-count`), but am leaning against. It's a little more immediately obvious what the count versions do, but will lead to obnoxious off by one issues when scripting since everything is zero-indexed.

I might also like to add a `--last-node` flag where you'll provide game/variation numbers and it tells you what number the last node is, but I'll need to think a little about what the interface for that will look like. I'll open an issue to remember to look into that later.

**Comment by julianandrews** [comment]
As I dig into implementing this I'm having the somewhat obvious realization that `--last-variation` requires a game number.

There are two obvious ways to do this:

```
sgf-render query --last-variation [game_num]
sgf-render query --last-variation --game [game_num]
```

where `game_num` defaults to `0` in either case.

I think I'm leaning towards the second option. It's a little more verbose, but most users won't be using it anyway (since most SGF files are single-game), and the more explicit version makes more sense for consistency with a potential `--last-node` flag that will need both a game and variation.

**Comment by vabue** [comment]
> As I dig into implementing this I'm having the somewhat obvious realization that --last-variation requires a game number.

It seems so. Getting the game number is also something that might be useful to get in query. 

Right now for the variations number I use bash oneliner which might be useful for someone, so I'll put it here:

```
sgf-render query "$file" | tail -n 1 | grep -o "v[0-9]*" | sed 's/v//' 
```

And as an example of usage, exporting all variants for all files in the pattern:
```
for file in prob*.sgf; do echo "Processing $file"; sgf-render -s -n 0 "$file" -o "${file%.sgf}-problem.svg"; last_var=$(sgf-render query "$file" | tail -n 1 | grep -o "v[0-9]*" | sed 's/v//'); for ((v=0; v<=last_var; v++)); do sgf-render -s -n last -v "$v" --move-numbers "$file" -o "${file%.sgf}-v$v.svg"; done; done
```

**Comment by julianandrews** [comment]
I've just pushed what should be a fix for this. If you're up for compiling from source, you should be able to try it out now!

I plan to make a new release soon, but want to fix the other bug first, and may not have time to get to that today.
