### ISSUE TITLE
would be better if it could respect of tradition convention

### ISSUE THREAD

**Issue by tdnetdog** [julianandrews/sgf-render#6]
with 02.sgf , we show step 1 without black stone outline, which should be shown as custom tradition convention

with 01.sgf , we show even no step 1, as convention, we should show text "3 = 1 " at bottom, and step 3 is still on image with stone outline

[sgfs.zip](https://github.com/julianandrews/sgf-render/files/6992529/sgfs.zip)

**Comment by julianandrews** [comment]
These both sound like worthwhile changes. The support for the "3 = 1" text may be a bit - I want to add support for comments and annotations generally, and doing that will require coming up with a layout for the diagrams that will look good in all cases. 

I'm going to close this issue because I've opened two new issues for the specific changes!
